apiVersion: v1              # deploy - razvertivanie: what we do with pod if this fall down
kind: Service               #                         or how much copies we have the nginx
metadata:
  name: nginx-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:                 # attach to nginx
    app: nginx
  type: LoadBalancer        # distributes a load
  loadBalancerIP: 192.168.99.100
  # distributes a load
  ports:
    - protocol: TCP
      name: http            # name so that it can distinguish between ports
      port: 80              # which port do we want to open: 80 (outside world)
      targetPort: 80        # attach to port 80 in container
    - protocol: TCP
      name: https           # name so that it can distinguish between ports
      port: 443
      targetPort: 443
   # - protocol: TCP
    #  name: ssh
     # port: 22
      #targetPort: 22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:                    #where its get containers
      containers:
      - name: nginx
        image: nginx_image
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
       # - containerPort: 22