apiVersion: v1              # deploy - razvertivanie: what we do with pod if this fall down
kind: Service               #                         or how much copies we have the nginx
metadata:
  name: wp-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:                 # attach to php
    app: wp
  type: LoadBalancer        # distributes a load
  loadBalancerIP: 192.168.99.100
  ports:
    - protocol: TCP
      port: 5050              # which port do we want to open: 80 (outside world)
      targetPort: 5050        # attach to port 80 in container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
  labels:
    app: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp
  template:
    metadata:
      labels:
        app: wp
    spec:                    #where its get containers
      containers:
        - name: wp
          image: wp_image
          imagePullPolicy: Never
          ports:
            - containerPort: 5050