apiVersion: v1              # deploy - razvertivanie: what we do with pod if this fall down
kind: Service               #                         or how much copies we have the nginx
metadata:
  name: php-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:                 # attach to php
    app: php
  type: LoadBalancer        # distributes a load
  loadBalancerIP: 192.168.99.107
  ports:
    - protocol: TCP
      port: 5000              # which port do we want to open: 80 (outside world)
      targetPort: 5000        # attach to port 80 in container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:                    #where its get containers
      containers:
        - name: php
          image: php_image
          imagePullPolicy: Never
          ports:
            - containerPort: 5000