apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  ports:
    - protocol: TCP
      name: ftp
      port: 20
      targetPort: 20
    - protocol: TCP
      name: ftps
      port: 21
      targetPort: 21
    - protocol: TCP
      name: port-passv
      port: 21000
      targetPort: 21000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      name: ftps-pod
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          image: ftps_image
          imagePullPolicy: Never
          ports:
            - containerPort: 21
            - containerPort: 21000